### ISSUE TITLE
speedquest

### ISSUE THREAD

**Issue by morganherlocker** [mapbox/tile-cover#32]
This ticket is a master ticket capturing several improvements focused around making tile-cover fast with lines and polygons.
- [x] [scanline algorithm](https://github.com/mapbox/tile-cover/issues/20)
- [ ] [Active Edge Table scanline index](https://github.com/mapbox/tile-cover/issues/31)
- [x] [bresenham's line algorithm](https://github.com/mapbox/tile-cover/issues/28)
- [x] [bbox low zoom optimization](https://github.com/mapbox/tile-cover/issues/29)
- [x] [broad tests](https://github.com/mapbox/tile-cover/issues/30)

cc @yhahn @ingalls @sbma44 @karenzshea 

![](http://static.comicvine.com/uploads/scale_super/1/10369/615325-supesflash2.jpg)
